# Generated by Django 3.2.7 on 2021-12-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_user', models.IntegerField()),
                ('pid', models.IntegerField()),
            ],
            options={
                'unique_together': {('buy_user', 'pid')},
            },
        ),
    ]
