# Generated by Django 3.2.7 on 2021-12-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('purchase', '0002_alter_purchasereq_buy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereq',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
